# 도서정보(BOOK) / 저자정보(AUTHOR) / 판매 데이터(BOOK_SALES)

SELECT A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, SUM(B.SALES) AS SALES

FROM AUTHOR AS A JOIN ( SELECT X.AUTHOR_ID, X.CATEGORY, Y.SALES * X.PRICE AS SALES
                        FROM BOOK AS X JOIN BOOK_SALES AS Y
                        ON X.BOOK_ID = Y.BOOK_ID
                        WHERE SALES_DATE LIKE '2022-01%') AS B
                        
ON A.AUTHOR_ID = B.AUTHOR_ID
GROUP BY A.AUTHOR_ID, B.CATEGORY
ORDER BY A.AUTHOR_ID, B.CATEGORY DESC